"""add medico_id to exames

Revision ID: 6957c3f8d9dc
Revises: 402002eade1d
Create Date: 2026-05-31 16:16:38.965492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6957c3f8d9dc'
down_revision: Union[str, Sequence[str], None] = '402002eade1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exames', sa.Column('medico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exames', 'medicos', ['medico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exames', type_='foreignkey')
    op.drop_column('exames', 'medico_id')
    # ### end Alembic commands ###
